spring:
  servlet:
    multipart:
      max-file-size: 500000MB
      max-request-size: 1024MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.order_deletes: true
      hibernate.generate_statistics: true
      hibernate.jdbc.batch_size: 10000
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.lob.non_contextual_creation: true